using Domain;
using Microsoft.AspNetCore.Mvc;
using Persistence;
using System;
using System.Collections.Generic;

namespace API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class PostsController : ControllerBase
    {
        private readonly DataContext _context;

        public PostsController(DataContext context)
        {
            _context = context;
        }

        // GET api/posts
        [HttpGet(Name = "GetPosts")]
        public ActionResult<List<Post>> Get()
        {
            return _context.Posts.ToList();
        }

        // GET api/posts/{id}
        [HttpGet("{id}", Name = "GetById")]
        public ActionResult<Post> GetById(Guid id)
        {
            var post = _context.Posts.Find(id);
            if (post is null)
            {
                return NotFound();
            }

            return Ok(post);
        }

        // POST api/posts
        [HttpPost(Name = "Create")]
        public ActionResult<Post> Create([FromBody] Post request)
        {
            // Create a new Post object
            var post = new Post
            {
                // Assuming Id is generated by the database
                Title = request.Title,
                Body = request.Body,
                Date = request.Date // Change `delegate` to `Date` or appropriate property name
            };

            _context.Posts.Add(post);
            var success = _context.SaveChanges() > 0;

            if (success)
            {
                return CreatedAtAction(nameof(GetById), new { id = post.Id }, post); // Use CreatedAtAction for POST
            }

            throw new Exception("Error creating post");
        }
        //ok
        [HttpPut(name = "Update")]
        public ActionResult<Post> Update([FromBody]PostsController request)
        {
            var post = _context.Posts.Find(request.Id);
            if (post == null)
            {
                throw new Exception("Could not find post");
            }

            post.Title = request.Title != null ? request.Title : post.Title;
            post.Body = request.Body != null ? request.Body : post.Body;
            post.Date = request.Date != DateTime.MinValue ? request.Date : post.Date;

            var success = _context.SaveChanges() > 0;
            if (success)
            {
                return Ok(post);
            }

            throw new Exception("Error updating post");
        }
    }
}
